name: dpma
description: Flutter project with Mobx and Firebase auth.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.0.0+2

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  camera: ^0.9.4
  cupertino_icons: ^1.0.2
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  mobx: ^2.0.1
  flutter_mobx: ^2.0.0
  dio: ^4.0.0
  get_it: ^7.0.0
  path_provider: ^2.0.5
  connectivity_plus: ^2.3.0
  cached_network_image: ^3.2.0
  google_fonts: 2.1.1
  lottie: ^1.2.2
  sizer: ^2.0.14
  styled_text: ^5.1.0
  intl_phone_field: ^3.1.0
  firebase_core: ^1.10.0
  firebase_auth: ^3.3.0
  image_picker: ^0.8.4
  carousel_slider: ^4.1.1

dependency_overrides:
  firebase_messaging_platform_interface: 3.1.6
  firebase_storage_platform_interface: 4.0.14
  cloud_functions_platform_interface: 5.0.21
  cloud_firestore_platform_interface: 5.4.13
  firebase_auth_platform_interface: 6.1.11
  firebase_database_platform_interface: 0.2.0+5

dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.0.5+2
  hive_generator: ^1.1.1
  build_runner: ^2.1.8

  flutter_lints: ^1.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/lottie/

